# Bootstrap Kafka brokers
bootstrap.servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092

# The group ID is a unique identifier for the set of workers that form a single Kafka Connect cluster
group.id=1

# The converters specify the format of data in Kafka and how to translate it into Connect data
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true

# The internal converter used for offsets and config data is configurable and must be specified
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

# Store offsets, configs, and status in Kafka topics
offset.storage.topic=dbz_offsets
config.storage.topic=dbz_config
status.storage.topic=dbz_statuses

# Security settings for Confluent Cloud
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="APIKEY" password="API SECRET";

# Producer settings
producer.security.protocol=SASL_SSL
producer.sasl.mechanism=PLAIN
producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="APIKEY" password="API SECRET";

# Consumer settings
consumer.security.protocol=SASL_SSL
consumer.sasl.mechanism=PLAIN
consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="APIKEY" password="API SECRET";

# Timeouts
session.timeout.ms=45000
request.timeout.ms=60000
status.storage.topic=connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

# Flush much faster than normal, which is useful for testing/debugging
offset.flush.interval.ms=10000

# REST API configuration
rest.host.name=0.0.0.0
rest.port=8083