# Bootstrap Kafka brokers
bootstrap.servers=kafka:9092

# The group ID is a unique identifier for the set of workers that form a single Kafka Connect cluster
group.id=1

# The converters specify the format of data in Kafka and how to translate it into Connect data
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true

# The internal converter used for offsets and config data is configurable and must be specified
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

# Store offsets, configs, and status in Kafka topics
offset.storage.topic=connect-offsets
config.storage.topic=connect-configs
status.storage.topic=connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

# Flush much faster than normal, which is useful for testing/debugging
offset.flush.interval.ms=10000

# REST API configuration
rest.host.name=0.0.0.0
rest.port=8083